//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.15 at 11:52:16 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.morelandlabs.com/testRegistry", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.perfectoMobile.page.keyWord.provider.xsd;
